packages:
  - packages/xml-introspect

catalog:
  '@types/node': ^20.10.0
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  '@typescript-eslint/eslint-plugin': ^8.35.1
  '@typescript-eslint/parser': ^8.35.1
  '@vitest/browser': ^3.2.4
  '@vitest/coverage-v8': 3.2.4
  '@vitest/ui': 3.2.4
  comlink: ^4.4.2
  cross-env: ^7.0.3
  eslint: ^9.30.1
  typescript: 5.8.3
  vite: ^7.0.4
  vite-plugin-comlink: ^5.3.0
  vite-plugin-dts: ^4.5.4
  vitest: 3.2.4
  zod: ^4.0.17

onlyBuiltDependencies:
  - esbuild
